<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AspNet.Security.OAuth.Discord" Version="10.0.0" />
      <PackageReference Include="BeerCss.Blazor" Version="0.1.1-preview1" />
      <PackageReference Include="Blazor-ApexCharts" Version="7.0.0" />
      <PackageReference Include="Discord.Net" Version="3.20.1" />
      <PackageReference Include="QRCoder" Version="1.8.0" />
      <PackageReference Include="QRCoderNetCore" Version="1.0.0" />
      <PackageReference Include="Serilog" Version="4.4.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.SpectreConsole" Version="0.4.0" />
      <PackageReference Include="SolarCalculator" Version="3.6.1" />
      <PackageReference Include="SynesthesiaDev.Codon.Codon" Version="2026.925.0" />
      <PackageReference Include="SynesthesiaDev.ConfigLib" Version="2026.902.0" />
      <PackageReference Include="SynesthesiaDev.Nocturne.Database" Version="2026.1010.0" />
      <PackageReference Include="SynesthesiaDev.Synx.Codon" Version="2026.902.0" />
      <PackageReference Include="SynesthesiaUtils" Version="2026.925.0" />
    </ItemGroup>

</Project>
